version: '3.1'

services:
  mongo:
    image: mongo:6.0.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db  # Volumen para la persistencia de datos
    ports:
      - "27017:27017"  # Exponer el puerto 27017 para acceder a MongoDB

volumes:
  mongodb_data:  # Declaración del volumen
